name: my_workflow

on: push

jobs:
  job1:
    name: ubuntu job
    runs-on: ubuntu-latest
    steps:
      - name: step one
        run: date

  job2:
    name: windows job
    runs-on: windows-latest
    steps:
      - name: step one
        run: Get-Date

  job3:
    name: mac job
    runs-on: macos-latest
    steps:
      - name: step one
        run: date

  job4:
    name: final job
    needs: [job1, job2, job3]
    runs-on: macos-latest
    steps:
      - name: step one
        run: date